// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yparqvwqryaxpdyzlpif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwYXJxdndxcnlheHBkeXpscGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDc5MjQsImV4cCI6MjA2ODAyMzkyNH0.DJs_cbSwzu88SpbODuYBMbxrVt6PFbaSk2lpWAkEJUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});